/*
We are provided with a number N. Our task is to generate all the Hailstone Numbers from N and find the number of steps taken by N to reduce to

Collatz Conjecture: A problem posed by L. Collatz in 1937, also called the 3x+1 mapping, 3n+1 problem. Let N be a integer. According to Collatz conjecture, if we keep iterating N as following 
N = N / 2 // For Even N 
and N = 3 * N + 1 // For Odd N 
Our number will eventually converge to 1 irrespective of the choice of N. 
Hailstone Numbers: The sequence of integers generated by Collatz conjecture are called Hailstone Numbers.

QBA LIU 2023 --------------------------------------------------------------------------------------------------------------------
*/

#include<stdio.h>

int even(int num){
	// return 1 if num is even
	// return 0 if num is odd
	int out = 1;
	if (num%2 != 0){
		out = 0;
	}
	return out;
}

void hailstones(int N){

	printf("Hailstones\n");
	printf(".............\n");
	
	int steps = 0;
	
	while (N > 1){
		if (even(N) == 0){
			N = 3*N+1;
		}
		else {
			N = N/2;
		}
		printf("%d\n", N);
		printf("---------\n");
		steps = steps + 1;
	}
	printf("----------\n");
	printf("----------\n");
	printf("Number of steps: %d\n", steps);
}

int main(void){
	int n;
	printf("Enter an integer: \n");
	scanf("%d", &n);
	hailstones(n);
	return 0;
}
